### ISSUE TITLE
Docstring style

### ISSUE THREAD

**Issue by goanpeca** [beeware/travertino#1]
Just wondering if we are using pydocstyle with beekeeper

I kinda like the idea that docstrings are sentences, so they should end with a `.`

So seeing code like

```python
class Color:
    "A base class for all colorspace representations"
```

Makes me want it to be like:

```python
class Color:
    "A base class for all colorspace representations."
```

Maybe too nit-picky... but my 2 cents

**Comment by freakboy3742** [comment]
Yes, we should be. I slip sometimes unless there is automated tooling in place :-)

**Comment by freakboy3742** [comment]
I'm going to close this ticket as it's a bit of an open ended target - there will always be documentation to fix. PRs to correct documentation strings are always welcome.
