### ISSUE TITLE
Make a release for the `clear` method

### ISSUE THREAD

**Issue by mhsmith** [beeware/travertino#32]
Going by the changes directory, the only significant change since the last release was adding the `clear` method (#23), which happened over 2 years ago. I think this method is useful enough to justify doing a release now, unless there are some other changes planned in the near future. 

Travertino's own `remove` method only supports removing one child at a time. Toga has an override that accepts multiple items, so the best current alternative to `x.clear()` is `x.remove(*x.children.copy())`. But this is inconvenient if `x` is a long expression, and it's easy to forget the `copy` and end up removing things from the children list while iterating over it.

**Comment by freakboy3742** [comment]
+1. Definitely overdue for a release; the only hesitation I have is whether some of the core layout work that I'm looking at right now *might* need a change at the Travertine level; plus #6 (which is a fairly important feature that has been indirectly reported as a bug in Toga beeware/toga#1502).

**Comment by freakboy3742** [comment]
As for implementing `clear()` in terms of remove - I'm not sure that's the best approach. Yes, Toga overrides `remove()` to add specific behavior. However, `remove()` contains a call to `refresh()` to ensure that layouts are updated when a widget is removed from a layout - but we don't want to do a re-layout after every removal in a `clear()`. 

So - either we introduce an explicit extension API to Travertino to allow for subclasses (like Pack) to implement "post layout" activities on a per-item and per-layout activity, and invoke that API on every individual removal, and at the end of a individual and bulk removals... or we override `clear()` in Toga to call `super().clear()` as well as individual item removals. My inclination is that the latter will be much easier.

**Comment by freakboy3742** [comment]
@mhsmith It's definitely an API we could add. However, at this point, it's a Toga issue; I'll open a ticket there.

**Comment by freakboy3742** [comment]
See beeware/toga#1828
